-- FEED
DROP TABLE IF EXISTS Feed;
CREATE TABLE Feed(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name CHAR(255) NOT NULL,
	link TEXT NOT NULL,
	isRssFeed BOOLEAN NOT NULL DEFAULT 0
);

-- FEEDTAG
DROP TABLE IF EXISTS FeedTag;
CREATE TABLE FeedTag(
	feedId INTEGER NOT NULL,
	tagName CHAR(64) NOT NULL,
	FOREIGN KEY(feedId) REFERENCES Feed(id) ON DELETE CASCADE,
	FOREIGN KEY(tagName) REFERENCES Tag(name) ON DELETE CASCADE,
	PRIMARY KEY(feedId, tagName)
);
