services:
  api:
    build: 
      context: .
      target: dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: .
          target: .
          ignore:
            - README.md
