FROM alpine:3.23.4 AS base

RUN apk update && apk add --no-cache \
    libjwt2 \
    openssl \
    libpq \
    curl \
    imagemagick \
    libwebp \
    cjson

FROM base AS dev

RUN apk add --no-cache \
    alpine-sdk \
    libjwt2-dev \
    openssl-dev \
    postgresql-dev \
    curl-dev \
    imagemagick-dev \
    cjson-dev \
    pkgconfig \
    bear \
    gdb \
    nodejs \
    npm

WORKDIR /app

RUN mkdir -p bin obj/lib obj/endpoints obj/sql

COPY . .

RUN npx tabula-docs@0.1.6 validate docs/api.json

RUN bear -- make

EXPOSE 8000

# CMD ["./bin/serv_api"]
CMD ["tail", "-f", "/dev/null"]

FROM base AS run

RUN rm -rf /sbin/apk /etc/apk /lib/apk /usr/share/apk /var/lib/apk

WORKDIR /app

COPY --from=dev /app/bin /app/bin
COPY index.html .
COPY docs/ docs/

CMD ["/app/bin/serv_api"]

